// Collect every t("…") key in the web app into apps/web/src/i18n/strings.ts.
//
// That generated list is what the Language screen offers as a translation
// template and what it measures a catalog's coverage against — so "how much of
// the game is translated?" has a real answer instead of a guess.
//
//   npm run i18n         → rewrite the list
//   npm run i18n -- --check  → fail if it's stale (for CI)
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SRC = "apps/web/src";
const OUT = join(SRC, "i18n", "strings.ts");

function walk(dir) {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : p.endsWith(".ts") || p.endsWith(".tsx") ? [p] : [];
  });
}

// t("…") / t('…') / t(`…`) with no interpolation in the key itself
const CALL = /\b(?:t|msg)\(\s*(["'`])((?:\\.|(?!\1)[^\\])*)\1/g;

const found = new Set();
for (const file of walk(SRC)) {
  if (file.includes("/i18n/")) continue; // the catalogs themselves
  const src = readFileSync(file, "utf8");
  for (const m of src.matchAll(CALL)) {
    const raw = m[2];
    // skip identifiers passed through as variables, e.g. t(BIND_LABELS[a])
    if (!raw || !/[a-z]/i.test(raw)) continue;
    found.add(raw.replace(/\\"/g, '"').replace(/\\'/g, "'").replace(/\\n/g, "\n"));
  }
}

const sorted = [...found].sort((a, b) => a.localeCompare(b));
const body = `// GENERATED by scripts/extract-strings.mjs — run \`npm run i18n\` after changing UI text.
// Every translatable string in the app, in one place: the template a translator
// fills in, and the denominator for a catalog's coverage percentage.
export const STRINGS: readonly string[] = ${JSON.stringify(sorted, null, 2)};
`;

if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(OUT, "utf8");
    } catch {
      return "";
    }
  })();
  if (current !== body) {
    console.error(`${OUT} is out of date — run \`npm run i18n\``);
    process.exit(1);
  }
  console.log(`i18n strings up to date (${sorted.length})`);
} else {
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT} — ${sorted.length} strings`);
}
